[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.install]
cmds = ["dotnet restore"]

[phases.build]
cmds = ["dotnet publish -c Release -o output"]

[start]
cmd = "dotnet output/ConsumoAPI2.Api.dll"
